# Specify the GitLab CI/CD pipeline configuration
stages:
  - build
  - deploy

# Define job for building the Node.js application
build:
  stage: build
  script:
    - npm install  # Install dependencies
    - nx run services-common:build # Build the application artifacts
  artifacts:
    paths:
      - build/  # Specify the directory containing build artifacts

# Define job for running tests

# Define job for deploying the application
deploy:
  stage: deploy
  script:
    - npm install --production  # Install production dependencies
    - pm2 restart auto  # Restart the Node.js application using pm2
  only:
    - test_levis  # Deploy only when changes are pushed to the master branch
