stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - npm install --force
    - nx build services-common
  artifacts:
    paths:
      - /var/www/html/automation/gtstoinfor/dist/packages/services/common

deploy-job:
  stage: deploy
  script:
    - scp -r /var/www/html/automation/gtstoinfor/dist/packages/services/common root@68.183.86.255:/var/www/html/automation/gtstoinfor/dist/packages/services/
  environment: production
