# Define the stages of the CI/CD pipeline
stages:
  - deploy

# Define the deploy job
deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y npm git  # Install necessary dependencies
    - cd /var/www/html/automation/gtstoinfor  # Change directory to the project directory
    - git pull  # Pull changes from Git
    - npm install -g @nrwl/cli  # Install Nx globally
    - nx reset  # Reset Nx workspace
    - nx run services-common:build  # Build services-common
    - npm install -g pm2  # Install pm2 globally
    - pm2 restart auto  # Restart pm2 auto
  only:
    - master  # Deploy only when changes are pushed to the master branch
