stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_ENV: production

deploy:
  stage: deploy
  script:
    - echo "Changing directory to /var/www/html/pvh/gtstoinfor"
    - cd /var/www/html/deoc_scan_test/gtstoinfor

    - echo "Performing a git pull"
    - git pull

    - echo "Installing npm dependencies"
    - npm install --force

    - echo "Resetting Nx"
    - npx nx reset

    - echo "Checking if files are up to date"
    - |
      if git log -1 | grep -q "Already up to date."; then
        echo "No files modified"
        exit 0
      fi

    - echo "Building services"
    - npx nx run services-common:build

    - echo "Restarting PM2"
    - pm2 restart 1
  only:
    - test_levis
