export enum LifeCycleStatusEnum{
    OPEN = "OPEN",
    PO_RAISED = "PO_RAISED",
    GRN = "GRN",
    MATERIAL_ALLOCATED = "MATERIAL_ALLOCATED",
    MATERIAL_ISSUED = "MATERIAL_ISSUED",
    READY_FOR_PRODUCTION = "READY_FOR_PRODUCTION",
    LAYING = "LAYING",
    CUTTING = "CUTTING",
    SEWING = "SEWING",
    EMBLISHMENT = "EMBLISHMENT",
    FINISHING = "FINISHING",
    QUALITY_CONTROL = "QUALITY_CONTROL",
    PACKING = "PACKING",
    SHIPMENT = "SHIPMENT",
    READY_TO_DISPATCH = "READY_TO_DISPATCH",
    CLOSED = "CLOSED",
 }
 
 export const LifeCycleStatusDisplay = [
     { name: "OPEN", displayVal:'OPEN'},
     { name:'PO_RAISED', displayVal:'PO RAISED'},
     { name:'GRN', displayVal:'GRN'},
     { name:'MATERIAL_ALLOCATED', displayVal:'MATERIAL ALLOCATED'},
     { name:'MATERIAL_ISSUED', displayVal:'MATERIAL ISSUED'},
     { name:'READY_FOR_PRODUCTION', displayVal:'READY FOR PRODUCTION'},
     { name:'LAYING', displayVal:'LAYING'},
     { name:'CUTTING', displayVal:'CUTTING'},
     { name:'SEWING', displayVal:'SEWING'},
     { name:'EMBLISHMENT', displayVal:'EMBLISHMENT'},
     { name:'FINISHING', displayVal:'FINISHING'},
     { name:'QUALITY_CONTROL', displayVal:'QUALITY_CONTROL'},
     { name:'PACKING', displayVal:'PACKING'},
     { name:'SHIPMENT', displayVal:'SHIPMENT'},
     { name:'DISPATCH', displayVal:'DISPATCH'},
     { name:'CLOSED', displayVal:'CLOSED'},

 ]