export const MenusAndScopesEnum ={
    Menus: {
        'GlobalConfiguration' : 'GlobalConfiguration',
        'Masters' : 'Masters',
        'Fabric Development' : 'Fabric Development',
        'Sample Development' : 'Sample Development',
        'Material Creation'  :'Material Creation',
        'Style Management' : 'Style Management',
        'OrderManagement' : 'OrderManagement',
        'Product Structure' :'Product Structure',
        'User Management':'User Management',
        'Procurment':'Procurment',
        'Operation Tracking':'Operation Tracking'
        
    },
    SubMenus:{
        'Indent' : 'Indent',
        'Sample Development View' : 'Sample Development View',
        'RM Trim Inventory' : 'RM Trim Inventory',
        'RM Fabric Inventory ' : 'RM Fabric Inventory ',
        'Reclassification Approval' : 'Reclassification Approval',
        'Allocation Approval' : 'Allocation Approval',
        'Purchase Order' : 'Purchase Order',
        'Grn':"Grn",
        'Sample Material Status' :'Sample Material Status'
        // 'Attributes' : 'Attributes',
        // 'Buyers' : 'Buyers',
        // 'Buyers Destination' : 'Buyers Destination',
        // 'Company' : 'Company',
        // 'Company Division' : 'Company Division',
        // 'Currency' : 'Currency',
        // 'Delivery Method' : 'Delivery Method',
        // 'Delivery Terms' : 'Delivery Terms',
        // 'Destination' : 'Destination',
        // 'Employees' : 'Employees',
        // 'Factories' : 'Factories',
        // 'Locations' : 'Locations',
        // 'Payment Method' : 'Payment Method',
        // 'Payment Terms' : 'Payment Terms',
        // 'Package Terms' : 'Package Terms',
        // 'Taxes' : 'Taxes',
        // 'UOM' : 'UOM',
        // 'Vendors' : 'Vendors',
        // 'WareHouse' : 'WareHouse',
        // 'Account Control Head' : 'Account Control Head',
        // 'Brands' : 'Brands',
        // 'Buying House' : 'Buying House',
        // 'Colour' : 'Colour',
        // 'Commision' : 'Commision',
        // 'Custom Groups' : 'Custom Groups',
        // 'Department' : 'Department',
        // 'Fabric Finish Type' : 'Fabric Finish Type',
        // 'Fabric Structure' : 'Fabric Structure',
        // 'Fabric Sub Type' : 'Fabric Sub Type',
        // 'Fabric Type' : 'Fabric Type',
        // 'Fabric Weave' : 'Fabric Weave',
        // 'Fabrics' : 'Fabrics',
        // 'Garment' : 'Garment',
        // 'Garment Category' : 'Garment Category',
        // 'item' : 'item',
        // 'Item Categories' : 'Item Categories',
        // 'Item Sub Category' : 'Item Sub Category',
        // 'Liscence Type' : 'Liscence Type',
        // 'Operation Groups' : 'Operation Groups',
        // 'Operations' : 'Operations',
        // 'Profit Control Head' : 'Profit Control Head',
        // 'ROSL Groups' : 'ROSL Groups',
        // 'Sample Sub Types' : 'Sample Sub Types',
        // 'SampleTypes' : 'SampleTypes',
        // 'Size' : 'Size',
        // 'Fabric Development Request' : 'Fabric Development Request',
        // 'Fabric Approval' : 'Fabric Approval',
        // 'Sample Development' : 'Sample Development',
        // 'Fabric Creation' : 'Fabric Creation',
        // 'Item Creation' : 'Item Creation',
        // 'SKU Generation' : 'SKU Generation',
        // 'SKU List' : 'SKU List',
        // 'Style Order Creattion' : 'Style Order Creattion',
        // 'Style Order View' : 'Style Order View',
        // 'Trim Creation' : 'Trim Creation',
        // 'Components Mapping' : 'Components Mapping',
        // 'Operation Sequence' : 'Operation Sequence',
        // 'CO Amendment':'CO Amendment',
        // 'Features':'Features',
        // 'Settings':'Settings',
        // 'MOP  Generation':'MOP  Generation',
        // 'RM SKUs':'RM SKUs',
        // 'FG SKUs':'FG SKUs',
        // 'Customer Orders':'Customer Orders',
        // 'Trim Items(RM)':'Trim Items(RM)',
        // 'Fabric Items(RM)':'Fabric Items(RM)',
        // 'FG Items':'FG Items',
        // 'RM to FG Mapping':'RM to FG Mapping',
        // 'Users':'Users',
        // 'Group Tech Class':'Group Tech Class',
        // 'Search Group':'Search Group',
        // 'Hierarchy Level':'Hierarchy Level',
        // 'Procurment Group':'Procurment Group',
        // 'Product Group':'Product Group',
        // 'Item Type':'Item Type',
        // 'SMV Efficiency':'SMV Efficiency',
        // 'Composition':'Composition',
        // 'Range':'Range',
        // 'CO Types':'CO Types',
        // 'Business Area':'Business Area',
        // 'ItemGroup':'ItemGroup',
       

    },
    Scopes:{
        'Create':'Create',
        'Update':'Update',
        'View':'View',
        'Cancel':'Cancel',
        'fabricTab' : 'fabricTab',
        'trimTab' : 'trimTab',
        'allocation' : 'allocation',
        'reclassification' :'reclassification',
        'PendingPoTab' : 'PendingPoTab',
        'createPo':'createPo'
       
    },
    roles:{

       'FabricSourcing' : 'FabricSourcing',
       'TrimSourcingUser' : 'TrimSourcingUser',
       'Warehouse' : 'Warehouse',
        'MarketingMerchandiser' :'MarketingMerchandiser',
        'MarketingUser':'MarketingUser',
        'samplingAdmin':'samplingAdmin',
        'samplingTeam':'samplingTeam',
        'sourcingUser' : 'sourcingUser'

    }
     
}
