export const MenusAndScopesEnum ={
    Menus: {
        'GlobalConfiguration' : 'GlobalConfiguration',
        'Masters' : 'Masters',
        'Fabric Development' : 'Fabric Development',
        'Sample Development' : 'Sample Development',
        'Material Creation'  :'Material Creation',
        'Style Management' : 'Style Management'
        
    },
    SubMenus:{
        'Attributes' : 'Attributes',
        'Buyers' : 'Buyers',
        'Buyers Destination' : 'Buyers Destination',
        'Company' : 'Company',
        'Company Division' : 'Company Division',
        'Currency' : 'Currency',
        'Delivery Method' : 'Delivery Method',
        'Delivery Terms' : 'Delivery Terms',
        'Destination' : 'Destination',
        'Employees' : 'Employees',
        'Factories' : 'Factories',
        'Locations' : 'Locations',
        'Payment Method' : 'Payment Method',
        'Payment Terms' : 'Payment Terms',
        'Package Terms' : 'Package Terms',
        'Taxes' : 'Taxes',
        'UOM' : 'UOM',
        'Vendors' : 'Vendors',
        'WareHouse' : 'WareHouse',
        'Account Control Head' : 'Account Control Head',
        'Brands' : 'Brands',
        'Buying House' : 'Buying House',
        'Colour' : 'Colour',
        'Commision' : 'Commision',
        'Custom Groups' : 'Custom Groups',
        'Department' : 'Department',
        'Fabric Finish Type' : 'Fabric Finish Type',
        'Fabric Structure' : 'Fabric Structure',
        'Fabric Sub Type' : 'Fabric Sub Type',
        'Fabric Type' : 'Fabric Type',
        'Fabric Weave' : 'Fabric Weave',
        'Fabrics' : 'Fabrics',
        'Garment' : 'Garment',
        'Garment Category' : 'Garment Category',
        'item' : 'item',
        'Item Categories' : 'Item Categories',
        'Item Sub Category' : 'Item Sub Category',
        'Liscence Type' : 'Liscence Type',
        'Operation Groups' : 'Operation Groups',
        'Operations' : 'Operations',
        'Profit Control Head' : 'Profit Control Head',
        'ROSL Groups' : 'ROSL Groups',
        'Sample Sub Types' : 'Sample Sub Types',
        'SampleTypes' : 'SampleTypes',
        'Size' : 'Size',
        'Fabric Development Request' : 'Fabric Development Request',
        'Fabric Approval' : 'Fabric Approval',
        'Sample Development' : 'Sample Development',
        'Fabric Creation' : 'Fabric Creation',
        'Item Creation' : 'Item Creation',
        'SKU Generation' : 'SKU Generation',
        'SKU List' : 'SKU List',
        'Style Order Creattion' : 'Style Order Creattion',
        'Style Order View' : 'Style Order View',
        'Trim Creation' : 'Trim Creation',
        'Components Mapping' : 'Components Mapping',
        'Operation Sequence' : 'Operation Sequence',
    },
    Scopes:{
        'Create':'Create',
        'Update':'Update',
        'View':'View',
        'Cancel':'Cancel',
       
    },
    roles:{
       
        'Admin' : 'Admin',
        'crmBuyer' : 'crmBuyer',
    }
     
}
