import { PropertyEnum } from "../../enum";


export class RmCreationDTO{
    rmitemId:string;
    itemCode:string;
    itemCategoryId:number;
    pchId:number;
    facilityID:number;
    genericCode:string;
    structure:string;
    quality:string;
    description:string;
    itemIypeId:number;
    placement:string;
    fabricFinishId:number;
    responsible:string;
    devResponsible:string;
    basicUomId:number;
    altUomId:number;
    multiplicationFactor:string;
    currencyId:number;
    price:string;
    tax:string;
    purchasePriceQty:string;
    saleTax:string;
    exciseDuty:string;
    licenseId:number;
    property:PropertyEnum;
    SaleItem:string;
    wastage:string;
    costGroup:string;
    remarks:string;
    itemGroupId:number;
    useInOperation:string;
    isActive: boolean;
    createdUser: string;
    updatedUser: string;
    versionFlag: number;
    constructor(rmitemId:string,itemCode:string,itemCategoryId:number, pchId:number,facilityID:number,genericCode:string,structure:string,quality:string,description:string,itemIypeId:number,placement:string, fabricFinishId:number,responsible:string,devResponsible:string, basicUomId:number,altUomId:number,multiplicationFactor:string,currencyId:number,price:string,tax:string,purchasePriceQty:string,saleTax:string,exciseDuty:string,licenseId:number,property:PropertyEnum,SaleItem:string,wastage:string, costGroup:string, remarks:string,itemGroup:number,useInOperation:string,isActive: boolean,createdUser: string,updatedUser: string,versionFlag: number){
        this.rmitemId=rmitemId;
        this.itemCode=itemCode;
        this.itemCategoryId=itemCategoryId;
        this.pchId=pchId;
        this.facilityID=facilityID;
        this.genericCode=genericCode;
        this.structure=structure;
        this.quality=quality;
        this.description=description;
        this.itemIypeId=itemIypeId;
        this.placement=placement;
        this.fabricFinishId=fabricFinishId;
        this.responsible=responsible;
        this.devResponsible=devResponsible;
        this.basicUomId=basicUomId;
        this.altUomId=altUomId;
        this.multiplicationFactor=multiplicationFactor;
        this.currencyId=currencyId;
        this.price=price;
        this.tax=tax;
        this.purchasePriceQty=purchasePriceQty;
        this.saleTax=saleTax;
        this.exciseDuty=exciseDuty;
        this.licenseId=licenseId;
        this.property=property;
        this.SaleItem=SaleItem;
        this.wastage=wastage;
        this.costGroup=costGroup;
        this.remarks=remarks;
        this.itemGroupId=itemIypeId;
        this.useInOperation=useInOperation;
        this.isActive=isActive;
        this.createdUser=createdUser;
        this.updatedUser=updatedUser;
        this.versionFlag=versionFlag;
    }
}