export enum VendorNameEnum {
    extractedDhl = "DHL FREIGHT",
    extractedDhlCourierfrieght = "DHL COURIER FRIEGHT",
    extractedDart = "DART",
    extractedExpeditors = "EXPEDITORS",
    extractedEfl = "EFL",
    extractedOocl = "OOCL",
    extractedNagel = "KUEHNE NAGEL",
    extractedApl = "APL",
    extractedMaersk = "MAERSK",
    extractedSrivaru = "SRIVARU",
    extractedKrsna = "KRSNA",
    extractedSriji="SRIJI",
    extractedKsr = "KSR",
    extractedDp = "DP",
    extractedNippon = "NIPPON",
    extractedVinayaka = "VINAYAKA",
    extractedWaymark = "WAYMARK",
    extractedLigi="LIGI",
    extractedNikkou="NIKKOU",
    extractedTriway="TRIWAY",
    extractedRingoCarago="RINGO CARGO",
    extractedMsn="MSN",
    extractedFredexFrieght="FREDEX FRIEGHT",
    extractedFredexCourier="FREDEX  COURIER",
    extractedDhlairduty="DHL AIR DUTY",
    extractedTotalTransport="TOTAL TRANSPORT",
    extractedSanjayForwarder="SANJAY FORWARDER",
    extractedOneTime="ONE TIME",
    extractedTiger="TIGER",
    extractedOia="OIA",
    extractedTextiles="TEXTILES COMMITEE",
    extractedToll="TOLL",
    extractedDelmar="DELMAR",
    extractedMgh="MGH",
    extractedLxpantos="LX PANTOS",
    extractedSavinoDell="SAVINO DELL",
    extractedNewblobe="NEW BLOBE",
    extracteddachser="DACHSER",
    extractedscanWell="SCANWELL",
    extractedMatrix="MATRIX",
    extractedRahat="RAHAT",



    extractedcogoPort="COGO PORT",
    extractedUnicorn="UNICORN",
    extractedUnique="UNIQUE",
    extractedTvs="TVS",
    extractedVelogicIndia="VELOGIC INDIA",
    extracteWiderlogistics="WIDER LOGISTICS",
    extractedWorldLine="WORLD LINE",
    extractedKwe="KWE",
    extractedUps = "UPS",
    extractedCube="20 CUBE",
    extractedAps="APS",
    extractChRowbin="CH ROWBIN",
    extractDBSCHENKAR="DB SCHENKAR",
    extractCeva="CEVA",

    
    

    

    

    extractedJeena="Jeena & Company",
    extractedKerryIndev="KERRY INDEV",
    extractedGateway='Gateway',
    extractedFederationofIndian='Federation of Indian',
    extractedLogWin='LOGWIN',
    extractedHellmann="HELLMANN",
    extractedGeodis="GEODIS",
    extractedJas="JAS",
    extractedGLOBELINK="GLOBELINK",
    
}
