import { SaveOrderDto } from "../models/save-order-dto";
import { OrdersChildEntity } from "../entities/orders-child.entity";
import { OrdersEntity } from "../entities/orders.entity";

export class OrdersChildAdapter {

    public convertDtoToEntity(dto:any,id:number,productionPlanId:number,month:number): any {
        const entity = new OrdersChildEntity()
        entity.year = dto.year;
        entity.planningSsnCd = dto.planningSsnCd
        entity.planningSsn = dto.planningSsn
        entity.tgtSsnCd = dto.tgtSsnCd
        entity.tgtSsn = dto.tgtSsn
        entity.bizCd = dto.bizCd
        entity.biz = dto.biz
        entity.planningRegionCode = dto.planningRegionCode
        entity.planningRegionName = dto.planningRegionName
        entity.channelCode = dto.channelCode
        entity.channelName = dto.channelName
        entity.department = dto.department
        entity.deptCd = dto.deptCd
        entity.Cls1_cd = dto.Cls1_cd
        entity.Cls2_cd = dto.Cls2_cd
        entity.gDept = dto.gDept
        entity.subCategory1 = dto.subCategory1
        entity.coreCategory = dto.coreCategory
        entity.subCategory2 = dto.subCategory2
        entity.subCategory3 = dto.subCategory3
        entity.productionCategoryFabric = dto.productionCategoryFabric
        entity.productionCategoryFabricProcessing = dto.productionCategoryFabricProcessing
        entity.productionCategorySewing = dto.productionCategorySewing
        entity.productionCategorySewingProcessing = dto.productionCategorySewingProcessing
        entity.planningSumCode = dto.planningSumCode
        entity.planningSum = dto.planningSum
        entity.localNameGhq = dto.localNameGhq
        entity.itemCd = dto.itemCd
        entity.item = dto.item
        entity.origPrice = dto.origPrice
        entity.mainSampleCode = dto.mainSampleCode
        entity.frFabricCode = dto.frFabricCode
        entity.frFabric = dto.frFabric
        entity.supplierRawMaterialCode = dto.supplierRawMaterialCode
        entity.supplierRawMaterial = dto.supplierRawMaterial
        entity.rawMaterialSupplierCode = dto.rawMaterialSupplierCode
        entity.rawMaterialSupplier = dto.rawMaterialSupplier
        entity.vendorCoode = dto.vendorCoode
        entity.vendor = dto.vendor
        entity.sewingFactoryCode = dto.sewingFactoryCode
        entity.sewingFactory = dto.sewingFactory
        entity.branchFactoryCode = dto.branchFactoryCode
        entity.branchFactory = dto.branchFactory
        entity.coeff = dto.coeff
        entity.itemBranchNumber = dto.itemBranchNumber
        entity.officialPlanStdQty = dto.officialPlanStdQty
        entity.OfficialPlanFabPrpPlnQty = dto.OfficialPlanFabPrpPlnQty
        entity.OfficialPlanPoPrSlsQty = dto.OfficialPlanPoPrSlsQty
        entity.officalPlanCoQty = dto.officalPlanCoQty
        entity.officalPlanStockQty = dto.officalPlanStockQty
        entity.slsStartDy = dto.slsStartDy
        entity.publishFlagForFactory = dto.publishFlagForFactory
        entity.publishDate = dto.publishDate
        entity.allcEndDy = dto.allcEndDy
        entity.slsEndDy = dto.slsEndDy
        entity.GWH = dto.GWH
        entity.orderPlanNumber = dto.orderPlanNumber
        entity.orderTiming = dto.orderTiming
        entity.swngPrdMonth = dto.swngPrdMonth
        entity.swngPrdWeek = dto.swngPrdWeek
        entity.orderPlanQty = dto.orderPlanQty
        entity.orderPlanQtyCoeff = dto.orderPlanQtyCoeff
        entity.trnspMthd = dto.trnspMthd
        entity.prodPlanType = dto.prodPlanType
        entity.ph1St = dto.ph1St
        entity.wh = dto.wh
        entity.whAct = dto.whAct
        entity.whAuto = dto.whAuto
        entity.yarnDlRequested = dto.yarnDlRequested
        entity.yarnDlAnswered = dto.yarnDlAnswered
        entity.yarnDlAuto = dto.yarnDlAuto
        entity.yarnProductionDueDateAuto = dto.yarnProductionDueDateAuto
        entity.yarnAutoReflectionDate = dto.yarnAutoReflectionDate
        entity.yarnActDy = dto.yarnActDy
        entity.yarnActQty = dto.yarnActQty
        entity.yarnOrderNumber = dto.yarnOrderNumber
        entity.yarnOrderStatus = dto.yarnOrderStatus
        entity.yarnDeliveryDate = dto.yarnDeliveryDate
        entity.fbrcDlRequested = dto.fbrcDlRequested
        entity.fbrcDlAnswered = dto.fbrcDlAnswered
        entity.fbrcDlAuto = dto.fbrcDlAuto
        entity.fbrcProductionDueDateAuto = dto.fbrcProductionDueDateAuto
        entity.fbrcAutoReflectionDate = dto.fbrcAutoReflectionDate
        entity.factoryCommentUpdateDate = dto.factoryCommentUpdateDate
        entity.fbrcActDy = dto.fbrcActDy
        entity.fbrcActQty = dto.fbrcActQty
        entity.fbrcOrderNumber = dto.fbrcOrderNumber
        entity.fbrcOrderStatus = dto.fbrcOrderStatus
        entity.fbrcDeliveryDate = dto.fbrcDeliveryDate
        entity.colorDlRequested = dto.colorDlRequested
        entity.colorDlAnswered = dto.colorDlAnswered
        entity.colorDlAuto = dto.colorDlAuto
        entity.colorProductionDueDateAuto = dto.colorProductionDueDateAuto
        entity.colorAutoReflectionDate = dto.colorAutoReflectionDate
        entity.colorActDy = dto.colorActDy
        entity.colorActQty = dto.colorActQty
        entity.colorOrderNumber = dto.colorOrderNumber
        entity.colorOrderStatus = dto.colorOrderStatus
        entity.colorDeliveryDate = dto.colorDeliveryDate
        entity.trimDlRequested = dto.trimDlRequested
        entity.trimDlAnswered = dto.trimDlAnswered
        entity.trimDlAuto = dto.trimDlAuto
        entity.trimProductionDueDateAuto = dto.trimProductionDueDateAuto
        entity.trimAutoReflectionDate = dto.trimAutoReflectionDate
        entity.trimActDy = dto.trimActDy
        entity.trimActQty = dto.trimActQty
        entity.trimOrderNumber = dto.trimOrderNumber
        entity.trimOrderStatus = dto.trimOrderStatus
        entity.trimDeliveryDate = dto.trimDeliveryDate
        entity.poDlRequested = dto.poDlRequested
        entity.poDlAnswered = dto.poDlAnswered
        entity.poDlAuto = dto.poDlAuto
        // entity.PO_EXFtotalAbnormalLT = dto.PO_EXFtotalAbnormalLT
        entity.poProductionDueDateAuto = dto.poProductionDueDateAuto
        entity.poAutoReflectionDate = dto.poAutoReflectionDate
        entity.poActDy = dto.poActDy
        entity.poActQty = dto.poActQty
        entity.poOrderNumber = dto.poOrderNumber
        entity.poOrderStatus = dto.poOrderStatus
        entity.assort1 = dto.assort1
        entity.assort2 = dto.assort2
        entity.nxAssort = dto.nxAssort
        entity.solid = dto.solid
        entity.orderPlanQtyStop = dto.orderPlanQtyStop
        entity.fixFlag = dto.fixFlag
        entity.alternativeFlag = dto.alternativeFlag
        entity.expressLineFlag = dto.expressLineFlag
        entity.factoryComment = dto.factoryComment
        entity.plannedEXF = dto.plannedEXF
        entity.exfEtd = dto.exfEtd
        entity.exfWh = dto.exfWh
        entity.sweingCountryRegion = dto.sweingCountryRegion
        entity.rewMaterialOriginal = dto.rewMaterialOriginal
        entity.itemDrop = dto.itemDrop
        entity.createDate = dto.createDate
        entity.createdUser = dto.userName
        entity.createdUserId = dto.createdUserId
        entity.createdUserName = dto.createdUserName
        entity.createFunction = dto.createFunction
        entity.updateDate = dto.updateDate
        entity.updatedUserId = dto.updatedUserId
        entity.updatedUserName = dto.updatedUserName
        // entity.updatedUserFunction = dto.updatedUserFunction
        entity.updateFunction = dto.updateFunction
        entity.countY = dto.countY
        entity.sample = dto.sample
        entity.exf = dto.exf
        entity.bddl = dto.bddl
        entity.bddlPast = dto.bddlPast
        entity.ltBdExf = dto.ltBdExf
        entity.newBddl = dto.newBddl
        entity.newLtBdExf = dto.newLtBdExf
        entity.ltPoExf = dto.ltPoExf
        entity.qtyLtBdExf = dto.qtyLtBdExf
        entity.qtyLtPoExf = dto.qtyLtPoExf
        entity.country2Y = dto.country2Y
        entity.phase = dto.phase
        entity.fileId = id
        entity.month= month
        entity.version = dto.version ? dto.version : 1
        const ordersEntity = new OrdersEntity();
        ordersEntity.productionPlanId = productionPlanId;
        entity.orders = ordersEntity;
        entity.fileId = id
        return entity
    
    }
}