

export const EMP_STR_EXP = /^\s*$/
export const ITEM_NO_EXP = 'VENDOR/DESCRIPTION'
export const ITEM_NO_INDEX = 0
export const ITEM_MATERIAL_INDEX = 'Material'
export const ITEM_DESCRIPTION_INDEX = ITEM_MATERIAL_INDEX + 1 // 2
export const ITEM_DELIVERYDATE_INDEX = ITEM_DESCRIPTION_INDEX + 1 // 3
export const ITEM_MODE_INDEX = ITEM_DELIVERYDATE_INDEX + 1 // 4 
export const ITEM_ACCEPTANCEDATE_INDEX = ITEM_MODE_INDEX + 1 // 5
export const ITEM_SHIP_TO_START_TEXT = 'CH' || 'US' || 'CA' || 'KR'
export const ITEM_SHIP_TO_START_INDEX = ITEM_SHIP_TO_START_TEXT + 1 // 6
export const ITEM_SHIP_TO_END_TEXT = 'Style #'
export const ITEM_SHIP_TO_END_INDEX = ITEM_SHIP_TO_END_TEXT // 6
export const ITEM_BILL_TO_START_TEXT = 'Factory/L.O.'
export const ITEM_BILL_TO_START_INDEX = ITEM_BILL_TO_START_TEXT + 1 // 6
export const ITEM_BILL_TO_END_TEXT = 'Agent/IMO'
export const ITEM_BILL_TO_END_INDEX = ITEM_BILL_TO_END_TEXT // 6
export const ITEM_TEXT_TEXT = 'ITEM TEXT'
export const ITEM_TEXT_END_TEXT = 'Last Updated:'
export const ITEM_TEXT_END_TEXT2 = 'Purchase Order Total'
export const UNWANTED_TEXT_1 = '- Nike provided'
export const UNWANTED_TEXT_2 = "- Primary salesman sample"
export const UNWANTED_TEXT_3 = "- Secondary salesman sample"
export const UNWANTED_TEXT_4 = "-SMU only"
export const UNWANTED_TEXT_5 = "-Promo only"
export const UNWANTED_TEXT_6 = "-Carryover colorway"
export const UNWANTED_TEXT_7 = "CONDITIONS."
export const UNWANTED_TEXT_8 = "Terms And Conditions:"
export const UNWANTED_TEXT_9 = "* End of Purchase Order *"
export const UNWANTED_TEXT_10 = "PackOne/SAP"
export const UNWANTED_TEXT_11 = "A DIVISION OF RALPH LAUREN CORP"
export const UNWANTED_TEXT_12 = "100 METRO BLVD, NUTLEY, NJ, 07110, US"
export const UNWANTED_TEXT_13 = "RALPH LAUREN CHILDRENSWEAR"
export const PO_DOC_DATE_TXT = 'Date Sent'
export const PO_DOC_DATE_INDEX = 1
export const SEASONYEAR_INDEX = 2
export const COLOR_DESC = 'Color Description'
export const CURR_INDEX = 4
export const INCOTERMS_INDEX = [5, 8]
export const FACTORYLOCATION_INDEX = 6
export const PO_NUMBER_TEXT = 'Style Name'
export const PO_NUMBER_INDEX = 1
export const SELLER_ADDRESS_START_TEXT = "SELLER:"
export const SELLER_ADDRESS_END_TEXT = "BUYER:"
export const ITEM_VARIANT_START_TEXT = "VENDOR/DESCRIPTION"

